backend:
  name: git-gateway
  branch: main # or your default branch
  repo: your-github-username/your-repo-name # optional if using Netlify Identity
  base_url: https://your-site.netlify.app # your deployed site URL
  auth_endpoint: api/auth # this is the redirect path

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
