name: Auto-Update Content
on:
  push:
    paths:
      - 'content/posts/**'

jobs:
  process-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git push

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate posts.json
        run: |
          npm install gray-matter
          node .github/scripts/generate-posts.js

      - name: Trigger Netlify Build
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './'
          production-branch: 'main'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}